name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: echo 'Hello world!'
